[visualization]
export = true
export_interval = 2

[[visualize_sim_object]]
name = "MyCell"
additional_data_members = [ "diameter_" ]

[[visualize_sim_object]]
name = "MyNeurite"
additional_data_members = [ ]

[[visualize_diffusion]]
name = "kSubstanceApical"
gradient = true

[[visualize_diffusion]]
name = "kSubstanceBasal"
gradient = true

